### ISSUE TITLE
Possible NullPointerException

### ISSUE THREAD

**Issue by duffj** [atam4j/atam4j#78] opened 2016-04-08 16:23 UTC
This may not actually be an atam4j problem, but I'm seeing an occasional one of these log messages:

```
INFO  [2016-04-06 15:03:13,888] [acceptance-tests-runner] me.atam.atam4j.logging.LoggingListener:  Test Test mechanism failed: Test mechanism
! java.lang.NullPointerException: null
! at me.atam.atam4j.TestRunListener.testFailure(TestRunListener.java:45) ~[user-cred-svc-acceptance-tests.jar:1.361.0]
```

**Comment by phillbarber** [comment] 2016-04-28 08:06
Hi @duffj, sorry for the delay in replying.  It looks like this could be caused by a null Failure object being passed to the listener.  What version of atam4j are you using?

Thanks

**Comment by anuragkapur** [comment] 2017-06-19 18:41
Closing issue due to lack of sufficient info

**Closed by anuragkapur** 2017-06-19 18:41 UTC
